#!/bin/sh

git clone git@github.com:folio-org/platform-core.git
git -C platform-core checkout snapshot

for m in `egrep '^\s+"@folio' ./platform-core/package.json\
 | cut -d\" -f 2\
 | sed -e 's/@folio\///'\
 | grep -v stripes`; 
do 
	git clone git@github.com:folio-org/ui-$m; 
done;
